//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeBrowserSpec) DeepCopyInto(out *RbeBrowserSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.RbeControlPlanePlacement.DeepCopyInto(&out.RbeControlPlanePlacement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeBrowserSpec.
func (in *RbeBrowserSpec) DeepCopy() *RbeBrowserSpec {
	if in == nil {
		return nil
	}
	out := new(RbeBrowserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeCluster) DeepCopyInto(out *RbeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeCluster.
func (in *RbeCluster) DeepCopy() *RbeCluster {
	if in == nil {
		return nil
	}
	out := new(RbeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RbeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeClusterList) DeepCopyInto(out *RbeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RbeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeClusterList.
func (in *RbeClusterList) DeepCopy() *RbeClusterList {
	if in == nil {
		return nil
	}
	out := new(RbeClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RbeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeClusterSpec) DeepCopyInto(out *RbeClusterSpec) {
	*out = *in
	in.Frontend.DeepCopyInto(&out.Frontend)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	in.Worker.DeepCopyInto(&out.Worker)
	in.Storage.DeepCopyInto(&out.Storage)
	in.Browser.DeepCopyInto(&out.Browser)
	out.Probe = in.Probe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeClusterSpec.
func (in *RbeClusterSpec) DeepCopy() *RbeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RbeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeClusterStatus) DeepCopyInto(out *RbeClusterStatus) {
	*out = *in
	out.Workers = in.Workers
	if in.LastProbe != nil {
		in, out := &in.LastProbe, &out.LastProbe
		*out = new(RbeProbeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeClusterStatus.
func (in *RbeClusterStatus) DeepCopy() *RbeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RbeClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeControlPlanePlacement) DeepCopyInto(out *RbeControlPlanePlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeControlPlanePlacement.
func (in *RbeControlPlanePlacement) DeepCopy() *RbeControlPlanePlacement {
	if in == nil {
		return nil
	}
	out := new(RbeControlPlanePlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeFrontendSpec) DeepCopyInto(out *RbeFrontendSpec) {
	*out = *in
	out.TLS = in.TLS
	out.JWT = in.JWT
	in.RbeControlPlanePlacement.DeepCopyInto(&out.RbeControlPlanePlacement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeFrontendSpec.
func (in *RbeFrontendSpec) DeepCopy() *RbeFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(RbeFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeJWTSpec) DeepCopyInto(out *RbeJWTSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeJWTSpec.
func (in *RbeJWTSpec) DeepCopy() *RbeJWTSpec {
	if in == nil {
		return nil
	}
	out := new(RbeJWTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeProbeSpec) DeepCopyInto(out *RbeProbeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeProbeSpec.
func (in *RbeProbeSpec) DeepCopy() *RbeProbeSpec {
	if in == nil {
		return nil
	}
	out := new(RbeProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeProbeStatus) DeepCopyInto(out *RbeProbeStatus) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeProbeStatus.
func (in *RbeProbeStatus) DeepCopy() *RbeProbeStatus {
	if in == nil {
		return nil
	}
	out := new(RbeProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeSchedulerSpec) DeepCopyInto(out *RbeSchedulerSpec) {
	*out = *in
	in.RbeControlPlanePlacement.DeepCopyInto(&out.RbeControlPlanePlacement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeSchedulerSpec.
func (in *RbeSchedulerSpec) DeepCopy() *RbeSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(RbeSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeStorageSpec) DeepCopyInto(out *RbeStorageSpec) {
	*out = *in
	in.RbeControlPlanePlacement.DeepCopyInto(&out.RbeControlPlanePlacement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeStorageSpec.
func (in *RbeStorageSpec) DeepCopy() *RbeStorageSpec {
	if in == nil {
		return nil
	}
	out := new(RbeStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeTLSSpec) DeepCopyInto(out *RbeTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeTLSSpec.
func (in *RbeTLSSpec) DeepCopy() *RbeTLSSpec {
	if in == nil {
		return nil
	}
	out := new(RbeTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeWorkerDrainSpec) DeepCopyInto(out *RbeWorkerDrainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeWorkerDrainSpec.
func (in *RbeWorkerDrainSpec) DeepCopy() *RbeWorkerDrainSpec {
	if in == nil {
		return nil
	}
	out := new(RbeWorkerDrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeWorkerSpec) DeepCopyInto(out *RbeWorkerSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Drain = in.Drain
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeWorkerSpec.
func (in *RbeWorkerSpec) DeepCopy() *RbeWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(RbeWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RbeWorkerStatus) DeepCopyInto(out *RbeWorkerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RbeWorkerStatus.
func (in *RbeWorkerStatus) DeepCopy() *RbeWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(RbeWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerAutoscaling) DeepCopyInto(out *WorkerAutoscaling) {
	*out = *in
	if in.Wake != nil {
		in, out := &in.Wake, &out.Wake
		*out = new(WorkerWake)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerAutoscaling.
func (in *WorkerAutoscaling) DeepCopy() *WorkerAutoscaling {
	if in == nil {
		return nil
	}
	out := new(WorkerAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPool) DeepCopyInto(out *WorkerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPool.
func (in *WorkerPool) DeepCopy() *WorkerPool {
	if in == nil {
		return nil
	}
	out := new(WorkerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolList) DeepCopyInto(out *WorkerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolList.
func (in *WorkerPoolList) DeepCopy() *WorkerPoolList {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolSpec) DeepCopyInto(out *WorkerPoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolSpec.
func (in *WorkerPoolSpec) DeepCopy() *WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolStatus) DeepCopyInto(out *WorkerPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolStatus.
func (in *WorkerPoolStatus) DeepCopy() *WorkerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerWake) DeepCopyInto(out *WorkerWake) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = make([]WorkerWakeGitHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ArcListener != nil {
		in, out := &in.ArcListener, &out.ArcListener
		*out = new(WorkerWakeArcListener)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerWake.
func (in *WorkerWake) DeepCopy() *WorkerWake {
	if in == nil {
		return nil
	}
	out := new(WorkerWake)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerWakeArcListener) DeepCopyInto(out *WorkerWakeArcListener) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerWakeArcListener.
func (in *WorkerWakeArcListener) DeepCopy() *WorkerWakeArcListener {
	if in == nil {
		return nil
	}
	out := new(WorkerWakeArcListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerWakeGitHub) DeepCopyInto(out *WorkerWakeGitHub) {
	*out = *in
	if in.Repos != nil {
		in, out := &in.Repos, &out.Repos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerWakeGitHub.
func (in *WorkerWakeGitHub) DeepCopy() *WorkerWakeGitHub {
	if in == nil {
		return nil
	}
	out := new(WorkerWakeGitHub)
	in.DeepCopyInto(out)
	return out
}
